enum Token {

    HTML,

    //FreeMarker
    DIRECTIVE_ASSIGN_START_OPEN,
    VARIABLE_NAME,
    VALUE,
    DIRECTIVE_TAG_CLOSE,
    DIRECTIVE_ASSIGN_END_OPEN,
    DIRECTIVE_ATTEMPT_START_OPEN,
    DIRECTIVE_ATEEMPT_END_OPEN,
    DIRECTIVE_ESCAPE_START_OPEN,
    DIRECTIVE_RECOVER_OPEN,
    DIRECTIVE_ESCAPE_END_OPEN,
    DIRECTIVE_COMPRESS_START_OPEN,
    DIRECTIVE_COMPRESS_END_OPEN,
    DIRECTIVE_NOESCAPE_START_OPEN,
    DIRECTIVE_NOESCAPE_END_OPEN,
    DIRECTIVE_FLUSH_OPEN,
    DIRECTIVE_TEMPLATE_INFO_OPEN,
    PARAMETER,
    DIRECTIVE_FUNCTION_DECLARATION_START_OPEN,
    NAME,
    DIRECTIVE_RETURN_OPEN,
    DIRECTIVE_FUNCTION_DECLARATION_END_OPEN,
    DIRECTIVE_GLOBAL_ASSIGN_START_OPEN,
    DIRECTIVE_GLOBAL_ASSIGN_START,


}
